#! /usr/bin/env bash
#formats json and rewrites file
tmpdir=$(mktemp)
tmpfile="$tmpdir/JSON-Format-$(date "+%Y-%m-%d-%H-%M-%S").json"
echo $tmpfile
jq < $1 > $tmpfile
if [ $? -eq 0 ]; then
	mv $tmpfile $1
fi

#clean up
rm -r $tmpdir
